import mongoose, { Schema, Document } from 'mongoose';

// A settlement represents one person paying another to resolve expense debts
// Generated by the min-cost flow algorithm in settlement.service.ts
export interface ISettlement extends Document {
    trip_id: string;
    from_user_id: string;   // who owes
    to_user_id: string;   // who receives
    amount: number;
    currency: string;
    status: 'pending' | 'initiated' | 'completed' | 'disputed';
    razorpay_order_id?: string;
    payment_id?: string;
    initiated_at?: Date;
    completed_at?: Date;
    created_at: Date;
}

const SettlementSchema = new Schema<ISettlement>({
    trip_id: { type: String, required: true, index: true },
    from_user_id: { type: String, required: true },
    to_user_id: { type: String, required: true },
    amount: { type: Number, required: true, min: 0.01 },
    currency: { type: String, default: 'INR' },
    status: {
        type: String,
        enum: ['pending', 'initiated', 'completed', 'disputed'],
        default: 'pending',
        index: true,
    },
    razorpay_order_id: String,
    payment_id: String,
    initiated_at: Date,
    completed_at: Date,
}, { timestamps: { createdAt: 'created_at', updatedAt: false } });

SettlementSchema.index({ trip_id: 1, status: 1 });
SettlementSchema.index({ from_user_id: 1, status: 1 });

export const SettlementModel = mongoose.model<ISettlement>('Settlement', SettlementSchema);
